  

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import MainNavbar from "@/components/mainNavbar";
import { usePathname } from "next/navigation";
import ClientNavbar from "@/components/clientNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTDORR+1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientNavbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}